EJERCICIO 2
a)

println(horas)
val horas = read float ()
for  (i = 40 && i 40)
if (i = 40 )
printl (salario por hora es $160)
else if (i  40)
println (salario por hora es $160 + 200 hora extra)
println (Horas de trabajo)
val Horas de trabajo = read float()
printl(salario obtenido por semana es )
for (i=40 )
 println (salario = horas  160)
printl(salario obtenido por semana es )
for (i  40 )
 println (salario = horas  160 && i + 200 )


b)
println (monto)
val monto = read float()
if (i = 500000)
println (monto - 55% - 30%)
println (cantidad a pagar )
println (empresa = monto-55%)
println (banco = monto- 30%)
println (credito fabricante = monto-15%)
else (i  500000)
println (monto -70% - 30%)
println (cantidad a pagar  )
println (empresa = monto-70%)
println (credito fabricante = monto-30%)
println (total a fabricante =  credito fabricante - 20%)
